### ISSUE TITLE
TikTok notifications

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/server#104]
## Current behavior
*Please describe how the feature works today*

Prefect Server / Cloud do not support TikTok notifications

## Proposed behavior
*Please describe your proposed change to the current behavior*

Prefect Server / Cloud support TikTok notifications

## Example
*Please give an example of how the enhancement would be useful*

Uh

## Motivation
*Please explain what prompted this enhancement*

https://www.youtube.com/watch?v=ZAPifDwKaXk

**Comment by joshmeek** [comment]
Am I being trolled?

**Comment by cicdw** [comment]
In TikTok lingo it's called a "duet" @joshmeek
