### ISSUE TITLE
Add healthcheck for apollo server

### ISSUE THREAD

**Issue by xaniasd** [PrefectHQ/server#127]
## Current behavior
at the moment, there is no endpoint for the apollo server, to indicate that it's alive. This creates problems in automated deployment of kubernetes agents. In specific, if the agent starts before apollo is ready, it will fail to register itself upon start up and never recover unless restarted.

## Proposed behavior
add endpoint indicating that apollo is ready to receive requests

## Example
It will allow using a reliable probe for liveliness and readiness in the context of a Kubernetes deployment

**Comment by joshmeek** [comment]
@xaniasd How are you running the server (docker compose, starting services directly, k8s, etc.)? Apollo natively exposes a route for the health check which is `/.well-known/apollo/server-health` and I believe you should be able to hit your apollo instance at that route to see if you get a 200 response code back.

**Comment by xaniasd** [comment]
hi @joshmeek thanks, wasn't aware of that. Does a 200 response imply that it's fully functional (i.e. ready to push queries upstream)? A quick test shows that this is the case, but good to double-check. 

I'm deploying the server on k8s so I'm looking for a reliable readiness probe for dependent components such as kubernetes agents.

**Comment by joshmeek** [comment]
Yes 200 should imply that apollo is good to go!
