### ISSUE TITLE
Bug: ValidationError ({'_schema': 'Invalid data type: None'})

### ISSUE THREAD

**Issue by vogre** [PrefectHQ/server#147]
## Description
When upgrading to version 0.13.8 (2020-11-29) and using mapped flows the log contains errors

```
Failed to retrieve task state with error: ValidationError({'_schema': 'Invalid data type: None'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 190, in initialize_run
    task_run_info = self.client.get_task_run_info(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1338, in get_task_run_info
    state = prefect.engine.state.State.deserialize(task_run_info.serialized_state)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/state.py", line 361, in deserialize
    state = StateSchema().load(json_blob)
  File "/usr/local/lib/python3.8/site-packages/marshmallow_oneofschema/one_of_schema.py", line 144, in load
    raise exc
marshmallow.exceptions.ValidationError: {'_schema': 'Invalid data type: None'}
```

And the tasks are pending without completing

## Expected Behavior
Flows written for 0.13.17 to keep working with the new version

## Reproduction
Sorry, I wasn't able to reproduce, as a "straightforward" mapping of a task over a list works well.

## Environment
prefecthq/prefect:0.13.18-python3.8
prefecthq/apollo:core-0.13.18
prefecthq/server:core-0.13.18
prefecthq/server:core-0.13.18
prefecthq/server:core-0.13.18
prefecthq/ui:core-0.13.18

**Comment by cicdw** [comment]
Hi @vogre - thanks for the bug report! This bug was recently fixed and the server images rebuilt; would you mind re-pulling `prefecthq/server:core-0.13.18` specifically and confirming that the issue is resolved for you?

**Comment by vogre** [comment]
Pulling 0.13.18 again fixed it, thank you!
