### ISSUE TITLE
Flow Run Page -> Task Run Name Search Fails with `task_run_name` argument

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/server#194]
## Description

From the Task Run table on the Flow Run page, it's possible to search for the name of a particular task run and get a list. However, the search fails to return results. The significant difference that I can see between this Flow Run and other Flow Runs is that I use the `task_run_name` feature to define my Task Run names using input arguments. No searches work for the Flow Runs in question on this page.

There's no error in chrome devtools that I can see.

I didn't open this ticket on the UI because I looked at the UI code and it seems to be doing everything correctly. Searching for dynamically generated names works at the flow level and I wonder if it's something about the nature of this query specifically.

## Expected Behavior

Return a subset of the Task Runs with the search results.

## Reproduction

https://cloud.prefect.io/prefect/flow-run/7fd9ed02-f19a-4aeb-a32a-ed7fa4b99908
![Screen Shot 2021-02-24 at 12 09 35 PM](https://user-images.githubusercontent.com/2325367/109107266-69480e00-76ff-11eb-9df8-332b0f95d1a6.png)
![Screen Shot 2021-02-24 at 12 09 18 PM](https://user-images.githubusercontent.com/2325367/109107284-706f1c00-76ff-11eb-9d84-a2a8ff7f5d9a.png)

## Environment
<!-- Any additional information about your environment
Prefect Cloud

**Comment by madkinsz** [comment]
@jlowin is it possible our index doesn't update when the name is changed? Could we pair on running an explain on this query?
