### ISSUE TITLE
Add submitted state locking to Prefect Server

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/server#203]
If a user has multiple agents with the same set of labels, multiple agents can pick up and start the same flow run. When running with Prefect Cloud, this will be caught via submitted state locking, so only one flow run can progress (and the others will abort). This feature was never ported over to Prefect Server, so currently users can end up with multiple executions of the same flow run.

**Comment by joe1981al** [comment]
Upvote this one as we are trying to make sure agents are in high availability in an ECS cluster, but are seeing logs indicating multiple agents are submitting a job for execution for the same flow.

Preventing this behavior would be great.
