### ISSUE TITLE
Explore flow concurrency limits per agent

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/server#213]
Some users are encountering issues where an Agent will deploy too many flows at once (often after some downtime) resulting in infrastructure collapse. Cloud flow concurrency limits would fix this by limiting concurrent flows by label (which the agent would have as well), but per #90 implementing label-based concurrency limits in Server is complicated and full of race conditions. An alternative solution is to limit the number of flows an _agent_ can spawn. This will prevent agents from spawning too many flows allowing other agents to process them or waiting until slots are available.

Since the `agent_id` is affixed to `FlowRuns` each agent can track how many flow runs it has spawned. The agent could just track this using local in-memory state but this would be hard to persist on agent restarts; additionally, this would be hard to generalize across all agent types. When an agent registers with the API, it will receive the same `agent_id` if the configuration values are the same making this solution robust. One concern is that users frequently start agents without names which can result in them sharing `agent_ids` despite being distinct agents. We will have to address this first, perhaps by requiring user-provided agent names.

Interestingly, this also will help with some user concerns about "work-balancing" in which they run many agents and desire for their flows to be equally distributed amongst them. Currently, agents collect work first-come-first-serve; with agent-level concurrency limits, a low limit can be set to encourage each agent to allow work to be collected by other agents. This is not a perfect balancing system, but will allow for rudimentary balancing where needed.

We will likely want to store agent concurrency limits in the `AgentConfig` (which is currently unused except for some beta Cloud features) as a `FLOW_CONCURRENCY_LIMIT: int` field. It would make sense to be able to define this from the CLI as well with a `--flow-limit <int>` argument which would override the `AgentConfig` value or allow you to set a limit without creating a separate config object. This would lead to some difficulty in display (in the UI) though, so perhaps we will not want to include it in the config and just include it in the `Agent` object.

This will likely require a lift for the `Agent` display in the UI to accommodate this additional information.

Inspired by @samreay and @jacksund at https://github.com/PrefectHQ/server/issues/90#issuecomment-796897974

This issue will track feasibility of implementation of this feature in Server (and consequently, Cloud).

**Comment by Samreay** [comment]
This sounds like a great lightweight way of adding a really useful feature. My agent runs as a service in the same swarm that the prefect server itself runs, and thus being able to limit a flow to having N active flows at once would make it so much easier to keep the swarm functioning and healthy.

**Comment by jacksund** [comment]
Thanks for the follow-up! Thought I would tack on some extra thoughts from a conceptual standpoint.

To address load-balancing across agents, it may be useful to make comparisons between a DaskWorker and a PrefectAgent. I like to think of Prefect+Dask as having two levels of executors: PrefectAgent is a "flow.run() executor" and DaskWorker is a "task.run() executor". Much like how DaskWorker has a `ThreadPool` that dictates the number of tasks, a PrefectAgent can have a `ThreadPool` or `FlowRunnerPool` for the number of flows.

Going off that `threadpool_size` (which would be the same as the `flow_limit`) could be detected automatically, rather than being an input supplied by `AgentConfig`. Currently, Prefect Agents assume a limitless `ThreadPool` and resources, which is why we run into trouble.

**Comment by Samreay** [comment]
Even if we separate out dask and the perfect agent, there would still be the issue of the flow process itself. For a docker agent, even with a remote dask executor, you should still get one container per flow, and those a computationally expensive and memory intensive.

**Comment by jacksund** [comment]
@Samreay So for `DockerAgents`, we'd have something like an `InstancePool` instead of a `ThreadPool`. The size of `InstancePool` is based off of local resources. Is that right?

**Comment by madkinsz** [comment]
@jacksund The 'Pool' approach is a nice idea but would require us to invent a pool type for every agent we introduce which may not make sense. It also means we have to implement a way for a 'Pool' to persistently track used resources across restarts i.e. if a you're using a `DockerAgent` is the `ContainerPool` the total count of containers on the system? how do we know which containers belong to that agent? what's a reasonable number of containers to run? Prefect currently isn't (and likely won't be) a resource manager, there are many tools that solve that problem better than we can. I do not think we should be attempting to infer values for this concurrency limit from system resources. I don't see an easy mapping; if you have a machine with 8 cores you may still want to run more than 8 concurrent flows.

**Comment by Samreay** [comment]
I think keeping it simple would be best to try and get something out. I simple maximum number of flows that an agent can launch and have active at once seems like that easiest path forward

**Comment by jacksund** [comment]
@madkinsz Yeah these are some really good points. I guess I was only thinking in the context of `LocalAgent` where local resources make good measure of `flow_run_limit`.  To your point about 8 cores != 8 concurrent flow limit, I agree. But testing Prefect may give us empirical data that shows something like "_Agents on 8 core machines w. 16G RAM are typically only stable up to 32 concurrent flows_" - or something like that to set a default value and allow the user to overwrite it if desired. If I were to really push this Pool idea, I could argue to add a default `UnlimitedPool` attached to the base Agent class -- so subclass agents aren't required to define a pool type.

But @Samreay is right. What I'm suggesting might be too much. The original comment of a simple `AgentConfig` kwarg is definitely the easiest. My suggestion is probably only relevant upon refactoring and major revisions (i.e. Prefect v1.0 or later).

**Comment by madkinsz** [comment]
See work in https://github.com/PrefectHQ/prefect/pull/4532
