### ISSUE TITLE
Inability to navigate back to Prefect Server without clearing cookies

### ISSUE THREAD

**Issue by mwheeler01** [PrefectHQ/server#239]
## Description

Running Prefect Server locally (with `prefect server start`) I went to the homepage and started clicking around. Eventually I opened the "Connection Menu" in the upper right hand corner and clicked Prefect Cloud to see what would happen. It redirected me to the login page at universal.prefect.io — fine. But I don't have a Prefect Cloud account, and I wanted to get back to my local Prefect Server page. Unfortunately, every time I tried to click the back button or navigate directly to localhost:8080, I got redirected straight back to universal.prefect.io. Worse, that page at universal.prefect.io provides no option to switch back to my local instance of Prefect Server, leaving me apparently stuck. Ultimately I had to clear my cookies to get back to the view I wanted.

## Expected Behavior

I expected to be able to navigate back to localhost:8080/default — either directly or using the back button — without getting sent back to unversal.prefect.io, or having to clear cookies.

## Reproduction

See above.

## Environment

macOS Big Sur 11.1, Google Chrome 89.0.4389.114, Prefect Server 2021.03.20

**Comment by madkinsz** [comment]
Thanks for the well written report -- there's an issue to track this in the UI at https://github.com/PrefectHQ/ui/issues/614 so I'll close this, but I agree this behavior is definitely not correct :)

**Comment by mwheeler01** [comment]
Oh true, this belonged in the other repo. Sorry about that, and thanks for your help!
