### ISSUE TITLE
Add Prometheus exporter API

### ISSUE THREAD

**Issue by nathanielobrown** [PrefectHQ/server#266]
## Current behavior
Today there is no way other than a custom exporter, to get metrics from Prefect into Prometheus.

## Proposed behavior
I think we should add a `/metrics` Prometheus API that exposes the following metrics high level:
* Counter for ask events (successes, failures, skips etc.) with task name, version etc. exposed
* Gauge of counts of tasks in different states with same task attributes as above. Useful for checking if tasks are becoming backed up
* Possibly histogram of execution times and maybe another of queue times?

I'm sure much more detail on what specific attributes should be included. Here are the docs for [Prometheus metric types](https://prometheus.io/docs/concepts/metric_types/), [writing a Prometheus exporter](https://prometheus.io/docs/instrumenting/writing_exporters/) and the [Prometheus export format](https://prometheus.io/docs/instrumenting/exposition_formats/)

## Example
I use Prometheus+Loki+Grafana for my monitoring solution. I also use Celery for task processing right now, but I'm interested in wholly or partially replacing Celery with Prefect. I have my Celery task event data exporting to Prometheus which is super useful for checking things are in a happy state and debugging issues. I can compare OS level metrics, with API metrics, with task metrics, with logs for everything to better understand how the different services affect each other.

## Notes
I realize that Prefect has a very nice UI with logging and metrics already, but I think many people would prefer to pipe this into Prometheus and use along side their other monitoring data, would love to here alternative perspectives.

I am not an expert on Prometheus or Prefect, but I'm posting this so a discussion can be started about the best interface for this. I would like to dig into the Prometheus/Prefect docs more to come up with a more fine-grained proposal.

**Comment by davzucky** [comment]
I would create a prometheus-export. The main reason for it is that in this case, it would work with Prefect cloud and server.

The main information we would like to get out from it is mainly about status of job/task which we could query using the GraphQL api.
Would be nice to have the subscribtion working as well so we would just have to listen to it rather than pulling

**Comment by Samreay** [comment]
This would be a great thing to see in a future release of prefect.

Having metrics available to count the number of successful/cancelled/failed tasks grouped by flow label would allow easy integration of prefect with other existing services and provide a nice way of hooking things up to PagerDuty. Right now, our current monitoring uses the slack notification feature within the flows, but a more generic solution would be prefered to standardise monitoring approaches.

In the nice to have category the timings for flows could be bucketed and exposed as well. Knowing which flows are taking more time or hanging would be a useful diagnostic that we could alert off as well.

**Comment by hozn** [comment]
@zanieb , was this closed because of the existence of https://github.com/aanogueira/prefect-exporter or is there some built-in integration as well?

**Comment by chayuto** [comment]
any update in this issue? what is the best approach to get prom metrics from prefect2 now?

**Comment by hozn** [comment]
@chayuto , FWIW, we ended up moving to use a push-based metrics approach in our pipeline as the primary pushgateway does not handle concurrent pushes of same meteics from different workers/agents. (We used opentelemetry with an otel aggregator for Prometheus.)

**Comment by chayuto** [comment]
> @chayuto , FWIW, we ended up moving to use a push-based metrics approach in our pipeline as the primary pushgateway does not handle concurrent pushes of same meteics from different workers/agents. (We used opentelemetry with an otel aggregator for Prometheus.)

Thank you for fast response and sharing

**Comment by davzucky** [comment]
We are doing the same thing. Just starting the Prefect server, agent, and worker with OTEL auto instrumentation provides us with metrics, tracing, and logs tags together, which is great.
