### ISSUE TITLE
Lonely pgpassword in towel helm chart

### ISSUE THREAD

**Issue by novotl** [PrefectHQ/server#315]
## Description

Talking helm charts here. Towel deployment gets only PGPASSWORD but not the rest of the PG connection string.
https://github.com/PrefectHQ/server/blob/938df638465cc920756cbd769f821f02233fd468/helm/prefect-server/templates/towel/deployment.yaml#L46-L48

It's suspicious that the towel deployment receives only the password to the PG database but not the rest of the database connection info. I think it may be some leftover configuration that was not deleted. I thought that towel doesn't talk to the database directly.

## Expected Behavior

The deployment should either receive full PG connection info (password + connection string) e.g. as in https://github.com/PrefectHQ/server/blob/e8845108459c6889b1e359b260681a91533173f8/helm/prefect-server/templates/hasura/deployment.yaml#L50-L54

or nothing.

**Comment by madkinsz** [comment]
Yeah I'm not sure why it'd need this. I'm happy to review a PR removing it if someone does some QA. Thanks for the issue!
