### ISSUE TITLE
Configure maximum size for artifact

### ISSUE THREAD

**Issue by joelluijmes** [PrefectHQ/server#319]
## Current behavior

Currently the accepted artifact has a maximum size of 1Mb. This check is hardcoded [here](https://github.com/PrefectHQ/server/blob/master/src/prefect_server/graphql/artifacts.py#L20-L21).

```python
if data_size > 1000000:  # 1 mb max
    raise ValueError("Artifact data payload exceedes 1Mb limit.")
```

## Proposed behavior

Preferably, it would be nice if we can configure the maximum size. I'm willing to submit a PR, but am unfamiliar with the codebase / graphql. I wouldn't really know the right way to retrieve a setting / environment variable in this place. Nor found an example in the other graphql files.

## Example

Submit bigger artifacts 🤓 

_Originally asked in [slack](https://prefect-community.slack.com/archives/C014Z8DPDSR/p1637752152103100)._

**Comment by madkinsz** [comment]
This is also enforced in the client so you don't waste time sending big artifacts that will be denied by the server, so we'd have to expose configuration in both places. I'm hesitant to say this makes sense as something to maintain. If you were to implement this, you'd introduce it to the prefect server config file and load it from the config object.

**Comment by madkinsz** [comment]
I actually don't see a check in the client as I thought, so this is actually not a real burden. (unless I'm missing it)

**Comment by joelluijmes** [comment]
I've previously made a PR that makes the body size of apollo configurable #296. I believe this is the last hurdle to tackle 🤞 , at least this is the current error that is thrown when creating my artifact.

Got a PR #320. Didn't think it was that easy to access the config. Let me know if its correct 😉
