### ISSUE TITLE
Can't use special characters in `--postgres-url` connection string (user name)

### ISSUE THREAD

**Issue by pierremonico** [PrefectHQ/server#330]
## Description
The Azure Database for PostgreSQL service uses a very untypical convention regarding usernames ([cf. point 2 of this section of the documentation](https://docs.microsoft.com/en-us/azure/postgresql/connect-python#get-database-connection-information)).

In essence, the **username** is always in the format `<admin-username>@<server-name>`, thus leading the full connection string to be in the format `postgres://<admin-username>@<server-name>:<password>@<server-url>:<port>/<db-name>`

I can confirm that my credentials work and that the username/connection string needs to be formatted this way since I am able to connect from a variety of clients.

The issue is that because of the strange username formatting  and the resulting connection string - the duplicate `@` in particular - it is impossible to run the server when passing this connection string to the `--postgres-url` flag.

- If I don't URL encode the string it will obviously be wrongly parsed and hasura spits `"internal":"invalid port number: \"<password>@<server-url>:<port>/<db-name>\"` (the part after `@` in the username is parsed as the server url.)
- If I URL encode (replacing `@` with `%40`), then it's the `graphql` service that spits `invalid interpolation syntax in '<connection-string>' at position 19` (position 19 is the `%`)

It is unfortunate that Azure uses such a strange format for the user name, but it's still one of the major three cloud providers; so I assume it's important to have this fixed.

## Expected Behavior
It should be possible to pass any URL encoded connection string to `--postgres-url` when running `prefect server start`.

This is especially relevant for Azure Database for PostgreSQL connection strings that use the strange `<admin-username>@<server-name>` user name format. 

## Reproduction

1. Spin up an Azure Database for PostgreSQL instance
2. Run `prefect server start --postgres-url <connection-string>` (the connection string being formatted as `postgres://<admin-username>@<server-name>:<password>@<server-url>:<port>/<db-name>`)

## Environment
Tried both on my Mac and on an Ubuntu VM, so I guess it's not relevant.

**Comment by madkinsz** [comment]
Hi! Can you share the traceback for the second case in which you get an invalid interpolation string message?

**Comment by pierremonico** [comment]
Hi @madkinsz, thanks for the reply. I gathered all the `graphql` related lines.
- I used `---` as a placeholder for when there were logs from other services in between
- I ended in `...` because it keeps on repeating
- I replaced only personal information with `x` so that you can see exactly how I pass the string (note the `%40` in the user name VS `@` to separate credentials from the server url, port and database name.

Is that what you need? 

```
graphql_1  |
graphql_1  | Running Alembic migrations...
---
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
---
graphql_1  |
graphql_1  | Could not upgrade the database!
---
t_graphql_1 exited with code 1
graphql_1  | Running Alembic migrations...
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
graphql_1  |
graphql_1  | Could not upgrade the database!
graphql_1  |
graphql_1  | Running Alembic migrations...
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
graphql_1  |
graphql_1  | Could not upgrade the database!
graphql_1  |
graphql_1  | Running Alembic migrations...
graphql_1  |
graphql_1  | Could not upgrade the database!
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
graphql_1  |
graphql_1  | Running Alembic migrations...
graphql_1  |
graphql_1  | Could not upgrade the database!
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
---
graphql_1  |
graphql_1  | Running Alembic migrations...
graphql_1  |
graphql_1  | Running Alembic migrations...
graphql_1  |
graphql_1  | Could not upgrade the database!
graphql_1  |
graphql_1  | Could not upgrade the database!
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
---
graphql_1  |
graphql_1  | Running Alembic migrations...
graphql_1  | Error: invalid interpolation syntax in 'postgres://xxxxxxx%40xxxxxxxxx:xxxxxxxxx@xxxxxxxxx.postgres.database.azure.com:5432/prefect_server' at position 19
graphql_1  |
graphql_1  | Could not upgrade the database!
---
...
```

**Comment by juloi** [comment]
Hey everyone,

The solution that has worked in the past for me is as follows:

```
cd PATH_TO_A_DIR
git clone https://github.com/PrefectHQ/server.git
cd server/
pip install -e .
export PG_PASSWORD="YOUR_PASSWORD"
prefect server start --expose --postgres-url postgresql://USER_NAME_PART_ONE%40USER_NAME_PART_TWO:$PG_PASSWORD@DOMAIN_OR_PUBLIC_IP:PORT/DB_NAME --external-postgres --no-upgrade
export PREFECT_SERVER__DATABASE__CONNECTION_URL="postgresql://USER_NAME_PART_ONE%40USER_NAME_PART_TWO:$PG_PASSWORD@DOMAIN_OR_PUBLIC_IP:PORT/DB_NAME"
prefect-server database upgrade
prefect backend server
```

It worked as recently as November 2021, and it depends purely on changes to the `server` codebase. The issue is related to Hasura.
