### ISSUE TITLE
prefect 0.15.12 - zombie processes from hasura container

### ISSUE THREAD

**Issue by hydrapolic** [PrefectHQ/server#335]
## Description

After upgrading from prefect 0.15.11 -> 0.15.12 we've observed over 800 zombie processes created in 2 hours time. They were created in the hasura container:

```
# docker exec -it prefect_hasura_1 bash

root@c9f9b79b27c9:/# apt-get update && apt-get -y install procps && ps auxww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 16.0  4.1 1077642404 202692 ?   Ssl  12:43   0:05 graphql-engine serve
root         7  0.2  0.0   5748  3580 pts/0    Ss   12:43   0:00 bash
root       412  0.0  0.0      0     0 ?        Z    12:44   0:00 [sh] <defunct>
root       481  0.0  0.0      0     0 ?        Z    12:44   0:00 [sh] <defunct>
root       494  0.0  0.0      0     0 ?        Z    12:44   0:00 [sh] <defunct>
root       495  0.0  0.0   9388  3088 pts/0    R+   12:44   0:00 ps auxww
```

After adding "init: true" to docker-compose hasura stanza it's mitigated (as suggested in https://github.com/PrefectHQ/prefect/pull/4142)

## Expected Behavior

No zombies hanging around.

## Reproduction

```
prefect server config > docker-compose.yml
docker-compose up
```

## Environment

Linux Gentoo, docker 20.10.9, docker-compose 1.29.2

**Comment by igonro** [comment]
Same problem here. I have 8180 zombie processes in 22h. It looks like it was solved in https://github.com/PrefectHQ/server/pull/191, but I still having this issue.

**Comment by hydrapolic** [comment]
https://github.com/PrefectHQ/server/pull/191 solved it for graphql / apollo, this is an issue with hasura.

**Comment by madkinsz** [comment]
Hi! Is this occurring in 0.15.13 as well where we've upgraded Hasura further? If so, I'd accept a fix that adds `tini`.

**Comment by igonro** [comment]
Hi @madkinsz! I was looking if I could implement the `tini` addition to hasura, but this is a little out of my field of knowledge.

After taking a look at #191, and the [docker-compose file](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/docker-compose.yml), it looks like this `tini` addition would have to be done in the [hasura/graphql-engine Dockerfile](https://github.com/hasura/graphql-engine) (?) or maybe Prefect should use its custom `hasura/graphql-engine` Dockerfile.

Maybe a faster approach could be to add `init: true` as @hydrapolic said, and maybe add an issue for this `tini` implementation. This way new people that start using Prefect wouldn't have to solve this problem. We have about 60.000 zombie processes in 1 week.

Thanks for your time!

**Comment by madkinsz** [comment]
Hey @igonro — I'm all for supporting it, but yeah we can't add it to the `Dockerfile` without creating our own. Perhaps someone should open a ticket in the Hasura repo and see what they think. 

We can add it to our compose file. I'm just a bit concerned about compatibility as it's not entirely clear to me which docker-compose versions support `init` e.g. https://stackoverflow.com/a/50357065/17398703. If you add `init: true` and set our required docker-compose version accordingly and explain which versions won't work with it in the PR body I will review it :)

**Comment by VincentAntoine** [comment]
Hi,

As we're not getting a response from the hasura guys in  the ticket I opened, I suggest using the `init: true` flag in Prefect's dockre-compose.

version 3.7 of compose file is needed to use init : https://docs.docker.com/compose/compose-file/compose-file-v3/#init

I can make the PR, but I'm not sure if it should be in prefectHQ/prefect or prefectHQ/server ?

**Comment by tomshaffner** [comment]
The 1.0 release seems to be out now; is the above fix in it? I see a merge above, but the issue is still open; is it targeted for the next release? And if so, ETA on that release?

**Comment by madkinsz** [comment]
1.0 doesn't contain this fix yet, we release roughly on a 2 week cycle.

This issue will remain open because the linked pull request only adds `init` via docker-compose which is used with `prefect server start` but will not affect Prefect Server users who start their server via other mechanisms.

**Comment by tomshaffner** [comment]
Understood. I use `prefect server start` though so will look forward to this fix hitting for me in the next week or two; thanks for the great work!
