### ISSUE TITLE
The latest Server release fails to start on M1 even when allocating 8GB RAM

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/server#336]
## Description
The community user got a `Connection refused error` when using the latest Prefect Core release and trying to start Server on Docker Desktop with docker-compose using the command `prefect server start`. 

```shell
graphql_1   | Could not upgrade the database!
graphql_1   | Error: HTTPConnectionPool(host='hasura', port=3000): Max retries exceeded with url: /v1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x400ad95710>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

The [link to the Slack thread](https://prefect-community.slack.com/archives/C014Z8DPDSR/p1642418682122100). I'm on Intel and therefore can't reproduce myself.

## Environment
Prefect 0.15.12 on M1 with Docker Desktop and docker-compose

**Comment by madkinsz** [comment]
Hasura 2.x is not compatible with M1 yet and the container will fail.

Using `prefect server config` then modifying the Hasura image to `hasura/graphql-engine:v2.1.0-beta.3` is the recommended workaround until they publish 2.1.0 and we can update the default.
