### ISSUE TITLE
default value for agent.resources.limits is invalid

### ISSUE THREAD

**Issue by kayahk** [PrefectHQ/server#344]
https://github.com/PrefectHQ/server/blob/ec4f49c24725d0a2d52719d4d678a3b821e390d7/helm/prefect-server/values.yaml#L372

the value of `agent.resources.limits.cpu` set in the values.yaml is lower than the (not included) default value for `agent.resources.requests.cpu` and causes an error:

`Error: Deployment.apps "prefect-server-agent" is invalid: spec.template.spec.initContainers[0].resources.requests: Invalid value: "150m": must be less than or equal to cpu limit`

Helm chart version: 2021.11.30

**Comment by madkinsz** [comment]
Thanks for the report! Happy to review a fix for this.
