### ISSUE TITLE
Maximum size for state payloads is limited to 1 mb

### ISSUE THREAD

**Issue by jonasmiederer** [PrefectHQ/server#349]
## Current behavior
Sometimes we are running flows with large input ( > 1 mb). These flow runs fail due to the size check in [GraphQL](https://github.com/PrefectHQ/server/blob/master/src/prefect_server/graphql/states.py#L29), which is capped to 1 mb.

Is there a reason behind this maximum input size?

If not, I could prepare a pull request similar to #320, which solves the same problem for artifacts.

## Proposed behavior
Make the maximum input size in the GraphQL check configurable

## Example
Current behaviour: 

```
GraphQL request:2:3
1 | mutation ($input: set_task_run_states_input!) {
2 |   set_task_run_states(input: $input) {
  |   ^
3 |     states {
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 628, in await_result
    return await result
  File "/prefect-server/src/prefect_server/graphql/extensions.py", line 52, in resolve
    result = await result
  File "/prefect-server/src/prefect_server/graphql/states.py", line 89, in resolve_set_task_run_states
    *[check_size_and_set_state(state_input) for state_input in input["states"]]
  File "/prefect-server/src/prefect_server/graphql/states.py", line 63, in check_size_and_set_state
    raise ValueError("State payload is too large.")
ValueError: State payload is too large.

```

**Comment by madkinsz** [comment]
I believe your database performance will be degraded if you place large state results in there. Can you use [result persistence](https://docs.prefect.io/core/concepts/results.html#pipeline-persisted-results) so the data on the state is only a reference? Or is the state large for another reason?

**Comment by jonasmiederer** [comment]
Thank you for pointing me to the result persistence information, I didn't know about that.

However we are facing the problem with large inputs to the flow, handled by a [Parameter](https://docs.prefect.io/core/concepts/parameters.html), so I guess result caching is not applicable here if I understood the concept correctly.

**Comment by madkinsz** [comment]
Ah yes, there's a similar issue at https://github.com/PrefectHQ/prefect/issues/4985

Large parameters will definitely impact performance. I think all parameters are passed alongside every task in the context, which can become an issue when using distributed executors. I'd recommend using another pattern if you can. For example, you could write the large parameter data to the KV Store then have the parameter be the "key" to read from and just retrieve it at the start of the flow with a task.

Out of curiosity, what are you storing in this parameter? Understanding this use-case will help us optimize parameters in the future.

**Comment by jonasmiederer** [comment]
Thank you Michael, I didn't know that parameters are passed to every single task. Then your point makes sense to me, impacting the overall performance is definitely not what I want to achieve  😉

We are using prefect to run a pipeline of heavy supply chain optimization tasks, for which we are receiving all the parameters and optimization objects by a 3rd party system, so our approach was to provide these values as a parameter to the flow run. But then I will have a look for an alternative concept.
