### ISSUE TITLE
Support bulk operation for delete_flow_run mutation.

### ISSUE THREAD

**Issue by asandeep** [PrefectHQ/server#62]
## Current behavior
The current `delete_flow_run` mutation allows one flow run to be deleted at a time. 

## Proposed behavior
Support bulk deletion of flow runs, something similar to what Hasura's auto generated schema provides. 

## Example
Please check this slack conversation: https://prefect-community.slack.com/archives/CL09KU1K7/p1598535130019500

**Comment by madkinsz** [comment]
@asandeep per the comment at https://github.com/PrefectHQ/server/pull/118#pullrequestreview-518205807 bulk operations are out of scope for us to implement right now and this can be implemented by users with direct access to the database. Sorry for the initial confusion!
